### ISSUE TITLE
Fails to compile on Crystal 1.0.0

### ISSUE THREAD

**Issue by hugopl** [kemalcr/kemal-session#98]
```
In lib/kemal-session/src/kemal-session/engines/memory.cr:70:16

 70 | @store.delete_if do |id, entry|
             ^--------
Error: undefined method 'delete_if' for Hash(String, String)
```
Despite of also using `json_mapping`

**Comment by hugopl** [comment]
Hmmm... this is probably fixed in 0.13.0, I noticed that sidekiq is using kenal 0.12.x just because kemal-csrf requires version 0.12.1

**Comment by hugopl** [comment]
Just tested, it's fixed on 1.0.0, the problem I have is with shard.yml from kemal-csrf shard.
